name: Run Checks

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  Run-Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Check Formatting
        run: |
          test -z $(go fmt .)

      - name: Run Tests
        run: |
          go test ./...

      - name: Check Build
        run: |
          go build .
